### ISSUE TITLE
FastifyPluginAsync is not assignable to type FastifyPluginCallback

### ISSUE THREAD

**Issue by hvqzao** [mgcrea/fastify-session#3]
Hi, I tried to troubleshoot an issue where every change to session data causes new session identifier to be issued regardless of using in-memory or your redis-store, so I cloned and locally build your repo, linked to my test repo and when I try to compile my typescript code I'm getting:
```
error TS2769: No overload matches this call.
Type 'FastifyPluginAsync<FastifySessionOptions, Server>' is not assignable to type 'FastifyPluginCallback<FastifySessionOptions, Server>'.
```
Eslint complains here:
```
fastify.register(FastifySession, {
                 ~~~~~~~~~~~~~~
```
Do you have any idea what might be the cause of either of these problems?

**Comment by mgcrea** [comment]
Are you using `yarn` as a package manager, you could be pulling a newer set of deps no respecting the `package-lock.json`.

Or maybe your NodeJS/NPM version is too old? (mine is `v14.15.3` and `v6.14.9`).

Tried to bump deps and regenerate a package-lock.json and still no issues.

**Comment by hvqzao** [comment]
Thank you for your feedback!

Mine NPM version is 6.14.10.

I've recreated my issue on separate repo (npm based) https://github.com/hvqzao/fastify-playground - if you'd like to check it (feel free to close the issue otherwise).

P.S. Keep up good work! I'm looking forward for option to disable rolling session (each time session is modified, new session key is issued, it can be observed e.g. on redis keys / Set-cookie in server response)

**Comment by mgcrea** [comment]
Hey, did not reproduce your issues after cloning your repo and pulling the last version of this package.

I've pushed a new v0.12.0 that have moved the libsodium crypto in an add-on package. 

This package now defaults to basic hmac (same as express-session).

It might fix your issue or re-signed sessions that is probably an artefact of libsodium's crypto.
Using hmac you should get a stable signature.

Nevertheless, there is probably improvements that can be done on regarding setting and signing an existing cookie.

Check the updated README to migrate your code.

**Comment by mgcrea** [comment]
@hvqzao I've pushed a new version that fixes the ID not being properly restored from an existing cookie/session (data was OK, id was always brand new), I think it should fix your issues.
